/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        foreground: 'hsl(var(--foreground))',
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        'on-primary-fixed-variant': '#004f56',
        'inverse-surface': '#213435',
        'secondary-fixed-dim': '#a5d1b4',
        'on-secondary-fixed': '#002111',
        'error-container': '#ffdad6',
        'outline-variant': '#bec8ca',
        'inverse-on-surface': '#e0f5f6',
        'on-surface': '#0b1e1f',
        'on-surface-variant': '#3f484a',
        'secondary-container': '#beeacc',
        surface: '#e8fdfe',
        'on-error-container': '#93000a',
        background: '#e8fdfe',
        'surface-bright': '#e8fdfe',
        'surface-container-highest': '#d2e6e7',
        'inverse-primary': '#87d3dc',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#001f23',
        'on-tertiary-container': '#fbffe5',
        'primary-container': '#2e7f88',
        'tertiary-fixed-dim': '#bfcd96',
        'on-primary': '#ffffff',
        'tertiary-container': '#6d7a4a',
        'surface-container-high': '#d7eced',
        'on-secondary-fixed-variant': '#274e39',
        'surface-container-low': '#e3f8f8',
        'surface-tint': '#076971',
        'tertiary-fixed': '#dbe9b0',
        'surface-container': '#ddf2f3',
        'primary-fixed-dim': '#87d3dc',
        'on-tertiary-fixed': '#161f00',
        primary: '#00666f',
        'on-tertiary-fixed-variant': '#404b21',
        tertiary: '#556134',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#a3eff9',
        error: '#ba1a1a',
        'surface-variant': '#d2e6e7',
        'surface-dim': '#c9dedf',
        outline: '#6f797a',
        'on-error': '#ffffff',
        'on-secondary': '#ffffff',
        'on-primary-container': '#f6feff',
        'secondary-fixed': '#c1edcf',
        'on-secondary-container': '#436b53',
        secondary: '#3f674f',
        'on-background': '#0b1e1f',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        margin: '2rem',
        xs: '0.25rem',
        lg: '1.5rem',
        gutter: '1.5rem',
        xl: '2.5rem',
        sm: '0.5rem',
        'max-width': '1280px',
        md: '1rem',
      },
      fontFamily: {
        h2: ['Manrope', 'sans-serif'],
        button: ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        h3: ['Manrope', 'sans-serif'],
        h1: ['Manrope', 'sans-serif'],
        'label-sm': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        sans: ['var(--font-sans)'],
        heading: ['var(--font-heading)'],
      },
      fontSize: {
        h2: [
          '36px',
          { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        button: [
          '16px',
          { lineHeight: '1', letterSpacing: '0.01em', fontWeight: '600' },
        ],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        h3: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        h1: [
          '48px',
          { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'label-sm': [
          '14px',
          { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '500' },
        ],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('tailwindcss-animate'),
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms'),
  ],
};
